package com.example.demo.entity;

import java.util.Date;

public class IssueAttachment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.id
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.attachment_type
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private Integer attachment_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.from_id
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private Long from_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.issue_id
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private Long issue_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.attachment_url
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private String attachment_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.creator
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.created_by
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private String created_by;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.created
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.modified_by
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private String modified_by;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.modified
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.status
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.from_type
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    private Integer from_type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_attachment
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public IssueAttachment(Long id, Integer attachment_type, Long from_id, Long issue_id, String attachment_url, Long creator, String created_by, Date created, String modified_by, Date modified, Integer status, Integer from_type) {
        this.id = id;
        this.attachment_type = attachment_type;
        this.from_id = from_id;
        this.issue_id = issue_id;
        this.attachment_url = attachment_url;
        this.creator = creator;
        this.created_by = created_by;
        this.created = created;
        this.modified_by = modified_by;
        this.modified = modified;
        this.status = status;
        this.from_type = from_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_attachment
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public IssueAttachment() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.id
     *
     * @return the value of issue_attachment.id
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.id
     *
     * @param id the value for issue_attachment.id
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.attachment_type
     *
     * @return the value of issue_attachment.attachment_type
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public Integer getAttachment_type() {
        return attachment_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.attachment_type
     *
     * @param attachment_type the value for issue_attachment.attachment_type
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setAttachment_type(Integer attachment_type) {
        this.attachment_type = attachment_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.from_id
     *
     * @return the value of issue_attachment.from_id
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public Long getFrom_id() {
        return from_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.from_id
     *
     * @param from_id the value for issue_attachment.from_id
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setFrom_id(Long from_id) {
        this.from_id = from_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.issue_id
     *
     * @return the value of issue_attachment.issue_id
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public Long getIssue_id() {
        return issue_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.issue_id
     *
     * @param issue_id the value for issue_attachment.issue_id
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setIssue_id(Long issue_id) {
        this.issue_id = issue_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.attachment_url
     *
     * @return the value of issue_attachment.attachment_url
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public String getAttachment_url() {
        return attachment_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.attachment_url
     *
     * @param attachment_url the value for issue_attachment.attachment_url
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setAttachment_url(String attachment_url) {
        this.attachment_url = attachment_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.creator
     *
     * @return the value of issue_attachment.creator
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.creator
     *
     * @param creator the value for issue_attachment.creator
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.created_by
     *
     * @return the value of issue_attachment.created_by
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public String getCreated_by() {
        return created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.created_by
     *
     * @param created_by the value for issue_attachment.created_by
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setCreated_by(String created_by) {
        this.created_by = created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.created
     *
     * @return the value of issue_attachment.created
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.created
     *
     * @param created the value for issue_attachment.created
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.modified_by
     *
     * @return the value of issue_attachment.modified_by
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public String getModified_by() {
        return modified_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.modified_by
     *
     * @param modified_by the value for issue_attachment.modified_by
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setModified_by(String modified_by) {
        this.modified_by = modified_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.modified
     *
     * @return the value of issue_attachment.modified
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.modified
     *
     * @param modified the value for issue_attachment.modified
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.status
     *
     * @return the value of issue_attachment.status
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.status
     *
     * @param status the value for issue_attachment.status
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.from_type
     *
     * @return the value of issue_attachment.from_type
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public Integer getFrom_type() {
        return from_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.from_type
     *
     * @param from_type the value for issue_attachment.from_type
     *
     * @mbg.generated Fri Feb 07 15:29:29 PST 2020
     */
    public void setFrom_type(Integer from_type) {
        this.from_type = from_type;
    }
}