package com.example.demo.entity;

import java.util.Date;

public class IssueAttachment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.id
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.attachment_type
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    private Integer attachment_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.issue_record_id
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    private Long issue_record_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.issue_id
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    private Long issue_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.attachment_url
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    private String attachment_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.creator
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.created_by
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    private String created_by;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.created
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.modified_by
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    private String modified_by;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.modified
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    private Date modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_attachment.is_disabled
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    private Boolean is_disabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_attachment
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public IssueAttachment(Long id, Integer attachment_type, Long issue_record_id, Long issue_id, String attachment_url, Long creator, String created_by, Date created, String modified_by, Date modified, Boolean is_disabled) {
        this.id = id;
        this.attachment_type = attachment_type;
        this.issue_record_id = issue_record_id;
        this.issue_id = issue_id;
        this.attachment_url = attachment_url;
        this.creator = creator;
        this.created_by = created_by;
        this.created = created;
        this.modified_by = modified_by;
        this.modified = modified;
        this.is_disabled = is_disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_attachment
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public IssueAttachment() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.id
     *
     * @return the value of issue_attachment.id
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.id
     *
     * @param id the value for issue_attachment.id
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.attachment_type
     *
     * @return the value of issue_attachment.attachment_type
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public Integer getAttachment_type() {
        return attachment_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.attachment_type
     *
     * @param attachment_type the value for issue_attachment.attachment_type
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public void setAttachment_type(Integer attachment_type) {
        this.attachment_type = attachment_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.issue_record_id
     *
     * @return the value of issue_attachment.issue_record_id
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public Long getIssue_record_id() {
        return issue_record_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.issue_record_id
     *
     * @param issue_record_id the value for issue_attachment.issue_record_id
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public void setIssue_record_id(Long issue_record_id) {
        this.issue_record_id = issue_record_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.issue_id
     *
     * @return the value of issue_attachment.issue_id
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public Long getIssue_id() {
        return issue_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.issue_id
     *
     * @param issue_id the value for issue_attachment.issue_id
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public void setIssue_id(Long issue_id) {
        this.issue_id = issue_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.attachment_url
     *
     * @return the value of issue_attachment.attachment_url
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public String getAttachment_url() {
        return attachment_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.attachment_url
     *
     * @param attachment_url the value for issue_attachment.attachment_url
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public void setAttachment_url(String attachment_url) {
        this.attachment_url = attachment_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.creator
     *
     * @return the value of issue_attachment.creator
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.creator
     *
     * @param creator the value for issue_attachment.creator
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.created_by
     *
     * @return the value of issue_attachment.created_by
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public String getCreated_by() {
        return created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.created_by
     *
     * @param created_by the value for issue_attachment.created_by
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public void setCreated_by(String created_by) {
        this.created_by = created_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.created
     *
     * @return the value of issue_attachment.created
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.created
     *
     * @param created the value for issue_attachment.created
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.modified_by
     *
     * @return the value of issue_attachment.modified_by
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public String getModified_by() {
        return modified_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.modified_by
     *
     * @param modified_by the value for issue_attachment.modified_by
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public void setModified_by(String modified_by) {
        this.modified_by = modified_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.modified
     *
     * @return the value of issue_attachment.modified
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.modified
     *
     * @param modified the value for issue_attachment.modified
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_attachment.is_disabled
     *
     * @return the value of issue_attachment.is_disabled
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public Boolean getIs_disabled() {
        return is_disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_attachment.is_disabled
     *
     * @param is_disabled the value for issue_attachment.is_disabled
     *
     * @mbg.generated Thu Feb 06 14:49:37 PST 2020
     */
    public void setIs_disabled(Boolean is_disabled) {
        this.is_disabled = is_disabled;
    }
}