package com.example.demo.entity;

public class UserSystemRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_system_role.id
     *
     * @mbg.generated Thu Feb 13 10:55:40 PST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_system_role.user_id
     *
     * @mbg.generated Thu Feb 13 10:55:40 PST 2020
     */
    private Long user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_system_role.system_role_id
     *
     * @mbg.generated Thu Feb 13 10:55:40 PST 2020
     */
    private Long system_role_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_system_role
     *
     * @mbg.generated Thu Feb 13 10:55:40 PST 2020
     */
    public UserSystemRole(Long id, Long user_id, Long system_role_id) {
        this.id = id;
        this.user_id = user_id;
        this.system_role_id = system_role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_system_role
     *
     * @mbg.generated Thu Feb 13 10:55:40 PST 2020
     */
    public UserSystemRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_system_role.id
     *
     * @return the value of user_system_role.id
     *
     * @mbg.generated Thu Feb 13 10:55:40 PST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_system_role.id
     *
     * @param id the value for user_system_role.id
     *
     * @mbg.generated Thu Feb 13 10:55:40 PST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_system_role.user_id
     *
     * @return the value of user_system_role.user_id
     *
     * @mbg.generated Thu Feb 13 10:55:40 PST 2020
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_system_role.user_id
     *
     * @param user_id the value for user_system_role.user_id
     *
     * @mbg.generated Thu Feb 13 10:55:40 PST 2020
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_system_role.system_role_id
     *
     * @return the value of user_system_role.system_role_id
     *
     * @mbg.generated Thu Feb 13 10:55:40 PST 2020
     */
    public Long getSystem_role_id() {
        return system_role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_system_role.system_role_id
     *
     * @param system_role_id the value for user_system_role.system_role_id
     *
     * @mbg.generated Thu Feb 13 10:55:40 PST 2020
     */
    public void setSystem_role_id(Long system_role_id) {
        this.system_role_id = system_role_id;
    }

    @Override
    public String toString() {
        return "UserSystemRole{" +
                "id=" + id +
                ", user_id=" + user_id +
                ", system_role_id=" + system_role_id +
                '}';
    }
}