package com.example.demo.mapper;

import com.example.demo.entity.IssueAttachment;
import org.apache.ibatis.jdbc.SQL;

public class IssueAttachmentSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_attachment
     *
     * @mbg.generated Wed Feb 05 15:03:51 PST 2020
     */
    public String insertSelective(IssueAttachment record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("issue_attachment");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getAttachment_type() != null) {
            sql.VALUES("attachment_type", "#{attachment_type,jdbcType=INTEGER}");
        }
        
        if (record.getIssue_record_id() != null) {
            sql.VALUES("issue_record_id", "#{issue_record_id,jdbcType=BIGINT}");
        }
        
        if (record.getIssue_id() != null) {
            sql.VALUES("issue_id", "#{issue_id,jdbcType=BIGINT}");
        }
        
        if (record.getAttachment_url() != null) {
            sql.VALUES("attachment_url", "#{attachment_url,jdbcType=VARCHAR}");
        }
        
        if (record.getCreator() != null) {
            sql.VALUES("creator", "#{creator,jdbcType=BIGINT}");
        }
        
        if (record.getCreated_by() != null) {
            sql.VALUES("created_by", "#{created_by,jdbcType=VARCHAR}");
        }
        
        if (record.getCreated() != null) {
            sql.VALUES("created", "#{created,jdbcType=TIMESTAMP}");
        }
        
        if (record.getModified_by() != null) {
            sql.VALUES("modified_by", "#{modified_by,jdbcType=VARCHAR}");
        }
        
        if (record.getModified() != null) {
            sql.VALUES("modified", "#{modified,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_attachment
     *
     * @mbg.generated Wed Feb 05 15:03:51 PST 2020
     */
    public String updateByPrimaryKeySelective(IssueAttachment record) {
        SQL sql = new SQL();
        sql.UPDATE("issue_attachment");
        
        if (record.getAttachment_type() != null) {
            sql.SET("attachment_type = #{attachment_type,jdbcType=INTEGER}");
        }
        
        if (record.getIssue_record_id() != null) {
            sql.SET("issue_record_id = #{issue_record_id,jdbcType=BIGINT}");
        }
        
        if (record.getIssue_id() != null) {
            sql.SET("issue_id = #{issue_id,jdbcType=BIGINT}");
        }
        
        if (record.getAttachment_url() != null) {
            sql.SET("attachment_url = #{attachment_url,jdbcType=VARCHAR}");
        }
        
        if (record.getCreator() != null) {
            sql.SET("creator = #{creator,jdbcType=BIGINT}");
        }
        
        if (record.getCreated_by() != null) {
            sql.SET("created_by = #{created_by,jdbcType=VARCHAR}");
        }
        
        if (record.getCreated() != null) {
            sql.SET("created = #{created,jdbcType=TIMESTAMP}");
        }
        
        if (record.getModified_by() != null) {
            sql.SET("modified_by = #{modified_by,jdbcType=VARCHAR}");
        }
        
        if (record.getModified() != null) {
            sql.SET("modified = #{modified,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }
}